name: Python greetings Workflow

# Controls when the workflow will run
on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
      - run: echo "Building docker image and pushing it to docker registry..."
  deploy-to-dev:
    runs-on: ubuntu-latest
    needs: [build-docker-image]
    steps:
      - uses: actions/checkout@v3
      - run: echo "Deploying Python microservice to DEV environment."
  tests-on-dev:
    runs-on: ubuntu-latest
    needs: [deploy-to-dev]
    steps:
      - uses: actions/checkout@v3
      - run: echo "Running api tests on DEV environment."
  deploy-to-stg:
    runs-on: ubuntu-latest
    needs: [tests-on-dev]
    steps:
      - uses: actions/checkout@v3
      - run: echo "Deploying Python microservice to STG environment."
  tests-on-stg:
    runs-on: ubuntu-latest
    needs: [deploy-to-stg]
    steps:
      - uses: actions/checkout@v3
        run: echo "Running api tests on STG environment."
  deploy-to-prod:
    runs-on: ubuntu-latest
    needs: [tests-on-stg]
    steps:
      - uses: actions/checkout@v3
      - run: echo "Deploying Python microservice to PROD environment."
  tests-on-prod:
    runs-on: ubuntu-latest
    needs: [deploy-to-prod]
    steps:
      - uses: actions/checkout@v3
      - run: echo "Running api tests on PROD environment."
