name: Python greetings Workflow

# Controls when the workflow will run
on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-docker-image:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
  deploy-to-dev:
    runs-on: self-hosted
    needs: [build-docker-image]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy
        with: 
          environment: "dev"
  tests-on-dev:
    runs-on: self-hosted
    needs: [deploy-to-dev]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test
        with: 
          environment: "dev"
  deploy-to-stg:
    runs-on: self-hosted
    needs: [tests-on-dev]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy
        with: 
          environment: "stg"
  tests-on-stg:
    runs-on: self-hosted
    needs: [deploy-to-stg]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test
        with: 
          environment: "stg"
  deploy-to-prod:
    runs-on: self-hosted
    needs: [tests-on-stg]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy
        with: 
          environment: "prod"
  tests-on-prod:
    runs-on: self-hosted
    needs: [deploy-to-prod]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test
        with: 
          environment: "prod"
